=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'cgi'

module Amos
  class DunningConfigurationsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Create the current organization's dunning configuration
    # @param create_dunning_configuration_request [CreateDunningConfigurationRequest] 
    # @param [Hash] opts the optional parameters
    # @return [DunningConfiguration]
    def create_dunning_configuration(create_dunning_configuration_request, opts = {})
      data, _status_code, _headers = create_dunning_configuration_with_http_info(create_dunning_configuration_request, opts)
      data
    end

    # Create the current organization&#39;s dunning configuration
    # @param create_dunning_configuration_request [CreateDunningConfigurationRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(DunningConfiguration, Integer, Hash)>] DunningConfiguration data, response status code and response headers
    def create_dunning_configuration_with_http_info(create_dunning_configuration_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DunningConfigurationsApi.create_dunning_configuration ...'
      end
      # verify the required parameter 'create_dunning_configuration_request' is set
      if @api_client.config.client_side_validation && create_dunning_configuration_request.nil?
        fail ArgumentError, "Missing the required parameter 'create_dunning_configuration_request' when calling DunningConfigurationsApi.create_dunning_configuration"
      end
      # resource path
      local_var_path = '/dunning_configuration'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
        header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(create_dunning_configuration_request)

      # return_type
      return_type = opts[:debug_return_type] || 'DunningConfiguration'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['X-Api-Key', 'bearerAuth']

      new_options = opts.merge(
        :operation => :"DunningConfigurationsApi.create_dunning_configuration",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DunningConfigurationsApi#create_dunning_configuration\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Retrieve the current organization's dunning configuration
    # @param [Hash] opts the optional parameters
    # @return [DunningConfiguration]
    def get_dunning_configuration(opts = {})
      data, _status_code, _headers = get_dunning_configuration_with_http_info(opts)
      data
    end

    # Retrieve the current organization&#39;s dunning configuration
    # @param [Hash] opts the optional parameters
    # @return [Array<(DunningConfiguration, Integer, Hash)>] DunningConfiguration data, response status code and response headers
    def get_dunning_configuration_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DunningConfigurationsApi.get_dunning_configuration ...'
      end
      # resource path
      local_var_path = '/dunning_configuration'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'DunningConfiguration'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['X-Api-Key', 'bearerAuth']

      new_options = opts.merge(
        :operation => :"DunningConfigurationsApi.get_dunning_configuration",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DunningConfigurationsApi#get_dunning_configuration\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Update the current organization's dunning configuration
    # @param update_dunning_configuration_request [UpdateDunningConfigurationRequest] 
    # @param [Hash] opts the optional parameters
    # @return [DunningConfiguration]
    def update_dunning_configuration(update_dunning_configuration_request, opts = {})
      data, _status_code, _headers = update_dunning_configuration_with_http_info(update_dunning_configuration_request, opts)
      data
    end

    # Update the current organization&#39;s dunning configuration
    # @param update_dunning_configuration_request [UpdateDunningConfigurationRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(DunningConfiguration, Integer, Hash)>] DunningConfiguration data, response status code and response headers
    def update_dunning_configuration_with_http_info(update_dunning_configuration_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DunningConfigurationsApi.update_dunning_configuration ...'
      end
      # verify the required parameter 'update_dunning_configuration_request' is set
      if @api_client.config.client_side_validation && update_dunning_configuration_request.nil?
        fail ArgumentError, "Missing the required parameter 'update_dunning_configuration_request' when calling DunningConfigurationsApi.update_dunning_configuration"
      end
      # resource path
      local_var_path = '/dunning_configuration'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
        header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(update_dunning_configuration_request)

      # return_type
      return_type = opts[:debug_return_type] || 'DunningConfiguration'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['X-Api-Key', 'bearerAuth']

      new_options = opts.merge(
        :operation => :"DunningConfigurationsApi.update_dunning_configuration",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:PATCH, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DunningConfigurationsApi#update_dunning_configuration\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
