=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'cgi'

module Amos
  class ProcessorTransactionsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # List all processor transactions
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :page The page of results to retrieve.
    # @option opts [Integer] :per_page Number of results per page.
    # @option opts [String] :payment_intent_id The ID of the payment intent to filter by
    # @option opts [String] :payment_method_id The ID of the payment method to filter by
    # @option opts [String] :payment_transaction_id The ID of the payment transaction to filter by
    # @return [ListProcessorTransactions]
    def list_processor_transactions(opts = {})
      data, _status_code, _headers = list_processor_transactions_with_http_info(opts)
      data
    end

    # List all processor transactions
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :page The page of results to retrieve.
    # @option opts [Integer] :per_page Number of results per page.
    # @option opts [String] :payment_intent_id The ID of the payment intent to filter by
    # @option opts [String] :payment_method_id The ID of the payment method to filter by
    # @option opts [String] :payment_transaction_id The ID of the payment transaction to filter by
    # @return [Array<(ListProcessorTransactions, Integer, Hash)>] ListProcessorTransactions data, response status code and response headers
    def list_processor_transactions_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ProcessorTransactionsApi.list_processor_transactions ...'
      end
      # resource path
      local_var_path = '/processor_transactions'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'page'] = opts[:'page'] if !opts[:'page'].nil?
      query_params[:'per_page'] = opts[:'per_page'] if !opts[:'per_page'].nil?
      query_params[:'payment_intent_id'] = opts[:'payment_intent_id'] if !opts[:'payment_intent_id'].nil?
      query_params[:'payment_method_id'] = opts[:'payment_method_id'] if !opts[:'payment_method_id'].nil?
      query_params[:'payment_transaction_id'] = opts[:'payment_transaction_id'] if !opts[:'payment_transaction_id'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'ListProcessorTransactions'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['X-Api-Key', 'bearerAuth']

      new_options = opts.merge(
        :operation => :"ProcessorTransactionsApi.list_processor_transactions",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ProcessorTransactionsApi#list_processor_transactions\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
