=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Amos::ChargesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ChargesApi' do
  before do
    # run before each test
    @api_instance = Amos::ChargesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ChargesApi' do
    it 'should create an instance of ChargesApi' do
      expect(@api_instance).to be_instance_of(Amos::ChargesApi)
    end
  end

  # unit tests for get_charge
  # Retrieve a charge
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Charge]
  describe 'get_charge test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_charges
  # List all charges
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The page of results to retrieve.
  # @option opts [Integer] :per_page Number of results per page.
  # @option opts [String] :payment_intent_id The ID of the payment intent to filter by
  # @return [ListCharges]
  describe 'list_charges test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_charge
  # Update a charge
  # @param id 
  # @param update_charge_request 
  # @param [Hash] opts the optional parameters
  # @return [Charge]
  describe 'update_charge test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
