=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Amos::DunningConfigurationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DunningConfigurationsApi' do
  before do
    # run before each test
    @api_instance = Amos::DunningConfigurationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DunningConfigurationsApi' do
    it 'should create an instance of DunningConfigurationsApi' do
      expect(@api_instance).to be_instance_of(Amos::DunningConfigurationsApi)
    end
  end

  # unit tests for create_dunning_configuration
  # Create the current organization&#39;s dunning configuration
  # @param create_dunning_configuration_request 
  # @param [Hash] opts the optional parameters
  # @return [DunningConfiguration]
  describe 'create_dunning_configuration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_dunning_configuration
  # Retrieve the current organization&#39;s dunning configuration
  # @param [Hash] opts the optional parameters
  # @return [DunningConfiguration]
  describe 'get_dunning_configuration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_dunning_configuration
  # Update the current organization&#39;s dunning configuration
  # @param update_dunning_configuration_request 
  # @param [Hash] opts the optional parameters
  # @return [DunningConfiguration]
  describe 'update_dunning_configuration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
