=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0
=end

require 'spec_helper'
require 'json'

# Unit tests for Amos::FileUploadsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FileUploadsApi' do
  before do
    # run before each test
    @api_instance = Amos::FileUploadsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FileUploadsApi' do
    it 'should create an instance of FileUploadsApi' do
      expect(@api_instance).to be_instance_of(Amos::FileUploadsApi)
    end
  end

  # unit tests for complete_file_upload
  # Complete a file upload
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [FileDownload]
  describe 'complete_file_upload test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_file_upload
  # Create a file upload
  # @param create_file_upload_request 
  # @param [Hash] opts the optional parameters
  # @return [FileUpload]
  describe 'create_file_upload test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_file_upload
  # Retrieve a file upload by ID
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [FileDownload]
  describe 'get_file_upload test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
