=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Amos::LegalEntityApplicationDocumentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LegalEntityApplicationDocumentsApi' do
  before do
    # run before each test
    @api_instance = Amos::LegalEntityApplicationDocumentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LegalEntityApplicationDocumentsApi' do
    it 'should create an instance of LegalEntityApplicationDocumentsApi' do
      expect(@api_instance).to be_instance_of(Amos::LegalEntityApplicationDocumentsApi)
    end
  end

  # unit tests for create_legal_entity_application_document
  # Create a legal entity application document
  # @param create_legal_entity_application_document_request 
  # @param [Hash] opts the optional parameters
  # @return [LegalEntityApplicationDocument]
  describe 'create_legal_entity_application_document test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_legal_entity_application_documents
  # List all legal entity application documents
  # @param legal_entity_application_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The page of results to retrieve.
  # @option opts [Integer] :per_page Number of results per page.
  # @return [ListLegalEntityApplicationDocuments]
  describe 'list_legal_entity_application_documents test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
