=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Amos::LegalEntityPrincipalsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LegalEntityPrincipalsApi' do
  before do
    # run before each test
    @api_instance = Amos::LegalEntityPrincipalsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LegalEntityPrincipalsApi' do
    it 'should create an instance of LegalEntityPrincipalsApi' do
      expect(@api_instance).to be_instance_of(Amos::LegalEntityPrincipalsApi)
    end
  end

  # unit tests for get_legal_entity_principal
  # Retrieve a legal entity principal by ID
  # @param id The ID of the legal entity principal to retrieve
  # @param [Hash] opts the optional parameters
  # @return [LegalEntityPrincipal]
  describe 'get_legal_entity_principal test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_legal_entity_principals
  # List all legal entity principals
  # @param legal_entity_id The ID of the legal_entity
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The page of results to retrieve.
  # @option opts [Integer] :per_page Number of results per page.
  # @return [ListLegalEntityPrincipals]
  describe 'list_legal_entity_principals test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
