=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0
=end

require 'spec_helper'
require 'json'

# Unit tests for Amos::LegalEntityApplicationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LegalEntityApplicationsApi' do
  before do
    # run before each test
    @api_instance = Amos::LegalEntityApplicationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LegalEntityApplicationsApi' do
    it 'should create an instance of LegalEntityApplicationsApi' do
      expect(@api_instance).to be_instance_of(Amos::LegalEntityApplicationsApi)
    end
  end

  # unit tests for approve_legal_entity_application
  # Approve a legal entity application
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [LegalEntityApplication]
  describe 'approve_legal_entity_application test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_legal_entity_application
  # Create a legal entity application
  # @param create_legal_entity_application_request 
  # @param [Hash] opts the optional parameters
  # @return [LegalEntityApplication]
  describe 'create_legal_entity_application test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_legal_entity_application
  # Retrieve a legal entity application by ID
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [LegalEntityApplication]
  describe 'get_legal_entity_application test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for submit_legal_entity_application
  # Submit a legal entity application
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [LegalEntityApplication]
  describe 'submit_legal_entity_application test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
