=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Amos::MerchantApplicationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MerchantApplicationsApi' do
  before do
    # run before each test
    @api_instance = Amos::MerchantApplicationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MerchantApplicationsApi' do
    it 'should create an instance of MerchantApplicationsApi' do
      expect(@api_instance).to be_instance_of(Amos::MerchantApplicationsApi)
    end
  end

  # unit tests for create_merchant_application
  # Create a merchant application
  # @param create_merchant_application_request 
  # @param [Hash] opts the optional parameters
  # @return [MerchantApplication]
  describe 'create_merchant_application test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_merchant_application
  # Retrieve a merchant application by ID
  # @param id The ID of the merchant application to retrieve
  # @param [Hash] opts the optional parameters
  # @return [MerchantApplication]
  describe 'get_merchant_application test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
