=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0
=end

require 'spec_helper'
require 'json'

# Unit tests for Amos::MerchantsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MerchantsApi' do
  before do
    # run before each test
    @api_instance = Amos::MerchantsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MerchantsApi' do
    it 'should create an instance of MerchantsApi' do
      expect(@api_instance).to be_instance_of(Amos::MerchantsApi)
    end
  end

  # unit tests for get_merchant
  # Retrieve a merchant by ID
  # @param id The ID of the merchant to retrieve
  # @param [Hash] opts the optional parameters
  # @return [Merchant]
  describe 'get_merchant test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_merchants
  # List all merchants
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The page of results to retrieve.
  # @option opts [Integer] :per_page Number of results per page.
  # @return [ListMerchants]
  describe 'list_merchants test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
