=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0
=end

require 'spec_helper'
require 'json'

# Unit tests for Amos::PaymentIntentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PaymentIntentsApi' do
  before do
    # run before each test
    @api_instance = Amos::PaymentIntentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentIntentsApi' do
    it 'should create an instance of PaymentIntentsApi' do
      expect(@api_instance).to be_instance_of(Amos::PaymentIntentsApi)
    end
  end

  # unit tests for cancel_payment_intent
  # Cancel a payment intent
  # @param id The ID of the payment intent to cancel
  # @param [Hash] opts the optional parameters
  # @return [PaymentIntent]
  describe 'cancel_payment_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for capture_payment_intent
  # Capture a payment intent
  # @param id The ID of the payment intent to capture
  # @param [Hash] opts the optional parameters
  # @return [PaymentIntent]
  describe 'capture_payment_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for confirm_embed_payment_intent
  # Confirm a payment intent
  # @param id The ID of the payment intent to confirm
  # @param confirm_payment_intent_request 
  # @param [Hash] opts the optional parameters
  # @return [PaymentIntent]
  describe 'confirm_embed_payment_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_payment_intent
  # Create a new payment intent
  # @param create_payment_intent_request 
  # @param [Hash] opts the optional parameters
  # @return [EmbedToken]
  describe 'create_payment_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_embed_payment_intent
  # Retrieve a payment intent by ID
  # @param id The ID of the payment intent to retrieve
  # @param [Hash] opts the optional parameters
  # @return [PaymentIntent]
  describe 'get_embed_payment_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_payment_intent
  # Retrieve a payment intent by ID
  # @param id The ID of the payment intent to retrieve
  # @param [Hash] opts the optional parameters
  # @return [PaymentIntent]
  describe 'get_payment_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_payment_intents
  # List payment intents
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The page of results to retrieve.
  # @option opts [Integer] :per_page Number of results per page.
  # @return [ListPaymentIntents]
  describe 'list_payment_intents test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
