=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Amos::PayoutsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PayoutsApi' do
  before do
    # run before each test
    @api_instance = Amos::PayoutsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PayoutsApi' do
    it 'should create an instance of PayoutsApi' do
      expect(@api_instance).to be_instance_of(Amos::PayoutsApi)
    end
  end

  # unit tests for bulk_create_payouts
  # Bulk create payouts
  # @param create_bulk_payouts_request 
  # @param [Hash] opts the optional parameters
  # @return [BulkCreatePayouts]
  describe 'bulk_create_payouts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_payout
  # Create a payout
  # @param create_payout_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_idempotency_key 
  # @return [Payout]
  describe 'create_payout test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_payout
  # Retrieve a payout by ID
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Payout]
  describe 'get_payout test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_payouts
  # List all payouts
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The page of results to retrieve.
  # @option opts [Integer] :per_page Number of results per page.
  # @option opts [String] :external_account_id The external account ID to filter by
  # @option opts [PayoutDirectionType] :direction The payout direction to filter by
  # @option opts [PayoutStateType] :state The payout state to filter by
  # @return [ListPayouts]
  describe 'list_payouts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
