=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0
=end

require 'spec_helper'
require 'json'

# Unit tests for Amos::ProcessorTransactionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ProcessorTransactionsApi' do
  before do
    # run before each test
    @api_instance = Amos::ProcessorTransactionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProcessorTransactionsApi' do
    it 'should create an instance of ProcessorTransactionsApi' do
      expect(@api_instance).to be_instance_of(Amos::ProcessorTransactionsApi)
    end
  end

  # unit tests for list_processor_transactions
  # List all processor transactions
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The page of results to retrieve.
  # @option opts [Integer] :per_page Number of results per page.
  # @option opts [String] :payment_intent_id The ID of the payment intent to filter by
  # @option opts [String] :payment_method_id The ID of the payment method to filter by
  # @option opts [String] :payment_transaction_id The ID of the payment transaction to filter by
  # @return [ListProcessorTransactions]
  describe 'list_processor_transactions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
