=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0
=end

require 'spec_helper'
require 'json'

# Unit tests for Amos::RenderTemplatesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RenderTemplatesApi' do
  before do
    # run before each test
    @api_instance = Amos::RenderTemplatesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RenderTemplatesApi' do
    it 'should create an instance of RenderTemplatesApi' do
      expect(@api_instance).to be_instance_of(Amos::RenderTemplatesApi)
    end
  end

  # unit tests for create_render_template
  # Create a new render template
  # @param create_render_template_request 
  # @param [Hash] opts the optional parameters
  # @return [RenderTemplate]
  describe 'create_render_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_render_token
  # Create a render token for render template
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [RenderToken]
  describe 'create_render_token test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_render_template
  # Retrieve a render template by ID
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [RenderTemplate]
  describe 'get_render_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_render_templates
  # List all render templates
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The page of results to retrieve.
  # @option opts [Integer] :per_page Number of results per page.
  # @option opts [String] :account_id 
  # @return [ListRenderTemplates]
  describe 'list_render_templates test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
