=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Amos::SetupIntentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SetupIntentsApi' do
  before do
    # run before each test
    @api_instance = Amos::SetupIntentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SetupIntentsApi' do
    it 'should create an instance of SetupIntentsApi' do
      expect(@api_instance).to be_instance_of(Amos::SetupIntentsApi)
    end
  end

  # unit tests for confirm_setup_intent_with_payment_method
  # Confirm a setup intent with a new payment method
  # @param id The ID of the setup intent to confirm
  # @param confirm_setup_intent_with_payment_method_request 
  # @param [Hash] opts the optional parameters
  # @return [SetupIntent]
  describe 'confirm_setup_intent_with_payment_method test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_setup_intent
  # Create a new setup intent
  # @param create_setup_intent_request 
  # @param [Hash] opts the optional parameters
  # @return [EmbedToken]
  describe 'create_setup_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_setup_intent
  # Retrieve a setup intent by ID
  # @param id The ID of the setup intent to retrieve
  # @param [Hash] opts the optional parameters
  # @return [SetupIntent]
  describe 'get_setup_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
