=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0
=end

require 'spec_helper'
require 'json'

# Unit tests for Amos::VoidsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VoidsApi' do
  before do
    # run before each test
    @api_instance = Amos::VoidsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VoidsApi' do
    it 'should create an instance of VoidsApi' do
      expect(@api_instance).to be_instance_of(Amos::VoidsApi)
    end
  end

  # unit tests for create_void
  # Create a void
  # @param create_void_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_idempotency_key 
  # @return [Void]
  describe 'create_void test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_void
  # Retrieve a void by ID
  # @param id The ID of the void to retrieve
  # @param [Hash] opts the optional parameters
  # @return [Void]
  describe 'get_void test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_voids
  # List all voids
  # @param customer_id The ID of the customer to filter by
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The page of results to retrieve.
  # @option opts [Integer] :per_page Number of results per page.
  # @option opts [String] :parent_transaction_id The ID of the original transaction to filter by
  # @return [ListVoids]
  describe 'list_voids test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_void
  # Update a void
  # @param id The ID of the void to update
  # @param update_void_request 
  # @param [Hash] opts the optional parameters
  # @return [Void]
  describe 'update_void test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
