=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Amos::WebhookRequestsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WebhookRequestsApi' do
  before do
    # run before each test
    @api_instance = Amos::WebhookRequestsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhookRequestsApi' do
    it 'should create an instance of WebhookRequestsApi' do
      expect(@api_instance).to be_instance_of(Amos::WebhookRequestsApi)
    end
  end

  # unit tests for list_webhook_requests
  # List all webhook requests
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The page of results to retrieve.
  # @option opts [Integer] :per_page Number of results per page.
  # @return [ListWebhookRequests]
  describe 'list_webhook_requests test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for resend_webhook_request
  # Resend webhook request by ID
  # @param id The ID of the webhook request to resend
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'resend_webhook_request test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retrieve_webhook_request
  # Get webhook request by ID
  # @param id The ID of the webhook request to retrieve
  # @param [Hash] opts the optional parameters
  # @return [WebhookRequest]
  describe 'retrieve_webhook_request test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
