=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0
=end

require 'spec_helper'
require 'json'

# Unit tests for Amos::WebhookAttemptsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WebhookAttemptsApi' do
  before do
    # run before each test
    @api_instance = Amos::WebhookAttemptsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhookAttemptsApi' do
    it 'should create an instance of WebhookAttemptsApi' do
      expect(@api_instance).to be_instance_of(Amos::WebhookAttemptsApi)
    end
  end

  # unit tests for list_webhook_attempts
  # List all webhook attempts
  # @param webhook_request_id The ID of the webhook request to filter by
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The page of results to retrieve.
  # @option opts [Integer] :per_page Number of results per page.
  # @return [ListWebhookAttempts]
  describe 'list_webhook_attempts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
