=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Amos::ConfirmSetupIntentInput
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Amos::ConfirmSetupIntentInput do
  let(:instance) { Amos::ConfirmSetupIntentInput.new }

  describe 'test an instance of ConfirmSetupIntentInput' do
    it 'should create an instance of ConfirmSetupIntentInput' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Amos::ConfirmSetupIntentInput)
    end
  end

  describe 'test attribute "moto"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "payment_method"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
