=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Amos::LegalEntityDocumentType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Amos::LegalEntityDocumentType do
  # let(:instance) { Amos::LegalEntityDocumentType.new }

  describe 'test an instance of LegalEntityDocumentType' do
    it 'should create an instance of LegalEntityDocumentType' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(Amos::LegalEntityDocumentType)
    end
  end

end
