=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Amos::OriginApplepayRegistrationStateType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Amos::OriginApplepayRegistrationStateType do
  # let(:instance) { Amos::OriginApplepayRegistrationStateType.new }

  describe 'test an instance of OriginApplepayRegistrationStateType' do
    it 'should create an instance of OriginApplepayRegistrationStateType' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(Amos::OriginApplepayRegistrationStateType)
    end
  end

end
