=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Amos::UpdateDunningConfigurationRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Amos::UpdateDunningConfigurationRequest do
  # let(:instance) { Amos::UpdateDunningConfigurationRequest.new }

  describe 'test an instance of UpdateDunningConfigurationRequest' do
    it 'should create an instance of UpdateDunningConfigurationRequest' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(Amos::UpdateDunningConfigurationRequest)
    end
  end

  describe 'test attribute "dunning_configuration"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
