=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Amos
  # Allowed payment method returned in API responses and render token JWT payloads.
  module AllowedPaymentMethod
    class << self
      # List of class defined in oneOf (OpenAPI v3)
      def openapi_one_of
        [
          :'AllowedBankAccountPaymentMethod',
          :'AllowedCardPaymentMethod',
          :'AllowedGooglePayPaymentMethod'
        ]
      end

      # Discriminator's property name (OpenAPI v3)
      def openapi_discriminator_name
        :'type'
      end

      # Discriminator's mapping (OpenAPI v3)
      def openapi_discriminator_mapping
        {
          :'bank_account' => :'AllowedBankAccountPaymentMethod',
          :'card' => :'AllowedCardPaymentMethod',
          :'googlepay' => :'AllowedGooglePayPaymentMethod'
        }
      end

      # Builds the object
      # @param [Mixed] Data to be matched against the list of oneOf items
      # @return [Object] Returns the model or the data itself
      def build(data)
        discriminator_value = data[openapi_discriminator_name]
        return nil if discriminator_value.nil?

        klass = openapi_discriminator_mapping[discriminator_value.to_s.to_sym]
        return nil unless klass

        Amos.const_get(klass).build_from_hash(data)
      end
    end
  end
end
