=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Amos
  class CardProfile < ApiModelBase
    attr_accessor :avs_check

    attr_accessor :avs_check_message

    attr_accessor :brand

    attr_accessor :card_holder_name

    attr_accessor :cvc_check

    attr_accessor :cvc_check_message

    attr_accessor :exp_month

    attr_accessor :exp_year

    attr_accessor :first6

    attr_accessor :funding

    attr_accessor :fingerprint

    attr_accessor :last4

    attr_accessor :state

    attr_accessor :three_d_secure_supported

    attr_accessor :token

    attr_accessor :wallet_provider

    attr_accessor :created_at

    attr_accessor :updated_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'avs_check' => :'avs_check',
        :'avs_check_message' => :'avs_check_message',
        :'brand' => :'brand',
        :'card_holder_name' => :'card_holder_name',
        :'cvc_check' => :'cvc_check',
        :'cvc_check_message' => :'cvc_check_message',
        :'exp_month' => :'exp_month',
        :'exp_year' => :'exp_year',
        :'first6' => :'first6',
        :'funding' => :'funding',
        :'fingerprint' => :'fingerprint',
        :'last4' => :'last4',
        :'state' => :'state',
        :'three_d_secure_supported' => :'three_d_secure_supported',
        :'token' => :'token',
        :'wallet_provider' => :'wallet_provider',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'avs_check' => :'String',
        :'avs_check_message' => :'String',
        :'brand' => :'String',
        :'card_holder_name' => :'String',
        :'cvc_check' => :'String',
        :'cvc_check_message' => :'String',
        :'exp_month' => :'Integer',
        :'exp_year' => :'Integer',
        :'first6' => :'String',
        :'funding' => :'String',
        :'fingerprint' => :'String',
        :'last4' => :'String',
        :'state' => :'String',
        :'three_d_secure_supported' => :'Boolean',
        :'token' => :'String',
        :'wallet_provider' => :'WalletProviderType',
        :'created_at' => :'Time',
        :'updated_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'avs_check_message',
        :'cvc_check_message',
        :'funding',
        :'fingerprint',
        :'three_d_secure_supported',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Amos::CardProfile` initialize method"
      end

      # Ignore attributes unknown to this client so additive API response fields remain backwards compatible.
      acceptable_attribute_map = self.class.acceptable_attribute_map
      acceptable_json_attribute_map = acceptable_attribute_map.invert
      attributes = attributes.each_with_object({}) { |(k, v), h|
        key = k.respond_to?(:to_sym) ? k.to_sym : k
        if acceptable_attribute_map.key?(key)
          h[key] = v
        elsif acceptable_json_attribute_map.key?(key)
          h[acceptable_json_attribute_map[key]] = v
        end
      }

      if attributes.key?(:'avs_check')
        self.avs_check = attributes[:'avs_check']
      end

      if attributes.key?(:'avs_check_message')
        self.avs_check_message = attributes[:'avs_check_message']
      end

      if attributes.key?(:'brand')
        self.brand = attributes[:'brand']
      end

      if attributes.key?(:'card_holder_name')
        self.card_holder_name = attributes[:'card_holder_name']
      end

      if attributes.key?(:'cvc_check')
        self.cvc_check = attributes[:'cvc_check']
      end

      if attributes.key?(:'cvc_check_message')
        self.cvc_check_message = attributes[:'cvc_check_message']
      end

      if attributes.key?(:'exp_month')
        self.exp_month = attributes[:'exp_month']
      end

      if attributes.key?(:'exp_year')
        self.exp_year = attributes[:'exp_year']
      end

      if attributes.key?(:'first6')
        self.first6 = attributes[:'first6']
      end

      if attributes.key?(:'funding')
        self.funding = attributes[:'funding']
      end

      if attributes.key?(:'fingerprint')
        self.fingerprint = attributes[:'fingerprint']
      end

      if attributes.key?(:'last4')
        self.last4 = attributes[:'last4']
      end

      if attributes.key?(:'state')
        self.state = attributes[:'state']
      end

      if attributes.key?(:'three_d_secure_supported')
        self.three_d_secure_supported = attributes[:'three_d_secure_supported']
      end

      if attributes.key?(:'token')
        self.token = attributes[:'token']
      end

      if attributes.key?(:'wallet_provider')
        self.wallet_provider = attributes[:'wallet_provider']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          avs_check == o.avs_check &&
          avs_check_message == o.avs_check_message &&
          brand == o.brand &&
          card_holder_name == o.card_holder_name &&
          cvc_check == o.cvc_check &&
          cvc_check_message == o.cvc_check_message &&
          exp_month == o.exp_month &&
          exp_year == o.exp_year &&
          first6 == o.first6 &&
          funding == o.funding &&
          fingerprint == o.fingerprint &&
          last4 == o.last4 &&
          state == o.state &&
          three_d_secure_supported == o.three_d_secure_supported &&
          token == o.token &&
          wallet_provider == o.wallet_provider &&
          created_at == o.created_at &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [avs_check, avs_check_message, brand, card_holder_name, cvc_check, cvc_check_message, exp_month, exp_year, first6, funding, fingerprint, last4, state, three_d_secure_supported, token, wallet_provider, created_at, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
