=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0
=end

require 'date'
require 'time'

module Amos
  class CreateLegalEntityApplicationInput
    attr_accessor :legal_name

    attr_accessor :entity_type

    attr_accessor :ownership_type

    attr_accessor :tax_id

    attr_accessor :contact_email

    attr_accessor :contact_phone

    attr_accessor :business_address_line1

    attr_accessor :business_address_line2

    attr_accessor :business_city

    attr_accessor :business_state

    attr_accessor :business_postal_code

    attr_accessor :business_country

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'legal_name' => :'legal_name',
        :'entity_type' => :'entity_type',
        :'ownership_type' => :'ownership_type',
        :'tax_id' => :'tax_id',
        :'contact_email' => :'contact_email',
        :'contact_phone' => :'contact_phone',
        :'business_address_line1' => :'business_address_line1',
        :'business_address_line2' => :'business_address_line2',
        :'business_city' => :'business_city',
        :'business_state' => :'business_state',
        :'business_postal_code' => :'business_postal_code',
        :'business_country' => :'business_country'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'legal_name' => :'String',
        :'entity_type' => :'String',
        :'ownership_type' => :'String',
        :'tax_id' => :'String',
        :'contact_email' => :'String',
        :'contact_phone' => :'String',
        :'business_address_line1' => :'String',
        :'business_address_line2' => :'String',
        :'business_city' => :'String',
        :'business_state' => :'String',
        :'business_postal_code' => :'String',
        :'business_country' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Amos::CreateLegalEntityApplicationInput` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Amos::CreateLegalEntityApplicationInput`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'legal_name')
        self.legal_name = attributes[:'legal_name']
      end

      if attributes.key?(:'entity_type')
        self.entity_type = attributes[:'entity_type']
      end

      if attributes.key?(:'ownership_type')
        self.ownership_type = attributes[:'ownership_type']
      end

      if attributes.key?(:'tax_id')
        self.tax_id = attributes[:'tax_id']
      end

      if attributes.key?(:'contact_email')
        self.contact_email = attributes[:'contact_email']
      end

      if attributes.key?(:'contact_phone')
        self.contact_phone = attributes[:'contact_phone']
      end

      if attributes.key?(:'business_address_line1')
        self.business_address_line1 = attributes[:'business_address_line1']
      end

      if attributes.key?(:'business_address_line2')
        self.business_address_line2 = attributes[:'business_address_line2']
      end

      if attributes.key?(:'business_city')
        self.business_city = attributes[:'business_city']
      end

      if attributes.key?(:'business_state')
        self.business_state = attributes[:'business_state']
      end

      if attributes.key?(:'business_postal_code')
        self.business_postal_code = attributes[:'business_postal_code']
      end

      if attributes.key?(:'business_country')
        self.business_country = attributes[:'business_country']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          legal_name == o.legal_name &&
          entity_type == o.entity_type &&
          ownership_type == o.ownership_type &&
          tax_id == o.tax_id &&
          contact_email == o.contact_email &&
          contact_phone == o.contact_phone &&
          business_address_line1 == o.business_address_line1 &&
          business_address_line2 == o.business_address_line2 &&
          business_city == o.business_city &&
          business_state == o.business_state &&
          business_postal_code == o.business_postal_code &&
          business_country == o.business_country
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [legal_name, entity_type, ownership_type, tax_id, contact_email, contact_phone, business_address_line1, business_address_line2, business_city, business_state, business_postal_code, business_country].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Amos.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
