=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Amos
  class LegalEntity < ApiModelBase
    attr_accessor :id

    attr_accessor :organization_id

    attr_accessor :legal_name

    attr_accessor :parent_legal_entity_id

    attr_accessor :entity_type

    attr_accessor :ownership_type

    attr_accessor :contact_email

    attr_accessor :contact_phone

    attr_accessor :business_address_line1

    attr_accessor :business_address_line2

    attr_accessor :business_city

    attr_accessor :business_state

    attr_accessor :business_postal_code

    attr_accessor :business_country

    attr_accessor :tax_id_last4

    attr_accessor :created_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'organization_id' => :'organization_id',
        :'legal_name' => :'legal_name',
        :'parent_legal_entity_id' => :'parent_legal_entity_id',
        :'entity_type' => :'entity_type',
        :'ownership_type' => :'ownership_type',
        :'contact_email' => :'contact_email',
        :'contact_phone' => :'contact_phone',
        :'business_address_line1' => :'business_address_line1',
        :'business_address_line2' => :'business_address_line2',
        :'business_city' => :'business_city',
        :'business_state' => :'business_state',
        :'business_postal_code' => :'business_postal_code',
        :'business_country' => :'business_country',
        :'tax_id_last4' => :'tax_id_last4',
        :'created_at' => :'created_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'organization_id' => :'String',
        :'legal_name' => :'String',
        :'parent_legal_entity_id' => :'String',
        :'entity_type' => :'LegalEntityEntityType',
        :'ownership_type' => :'LegalEntityOwnershipType',
        :'contact_email' => :'String',
        :'contact_phone' => :'String',
        :'business_address_line1' => :'String',
        :'business_address_line2' => :'String',
        :'business_city' => :'String',
        :'business_state' => :'String',
        :'business_postal_code' => :'String',
        :'business_country' => :'String',
        :'tax_id_last4' => :'String',
        :'created_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'parent_legal_entity_id',
        :'business_address_line2',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Amos::LegalEntity` initialize method"
      end

      # Ignore attributes unknown to this client so additive API response fields remain backwards compatible.
      acceptable_attribute_map = self.class.acceptable_attribute_map
      acceptable_json_attribute_map = acceptable_attribute_map.invert
      attributes = attributes.each_with_object({}) { |(k, v), h|
        key = k.respond_to?(:to_sym) ? k.to_sym : k
        if acceptable_attribute_map.key?(key)
          h[key] = v
        elsif acceptable_json_attribute_map.key?(key)
          h[acceptable_json_attribute_map[key]] = v
        end
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'organization_id')
        self.organization_id = attributes[:'organization_id']
      end

      if attributes.key?(:'legal_name')
        self.legal_name = attributes[:'legal_name']
      end

      if attributes.key?(:'parent_legal_entity_id')
        self.parent_legal_entity_id = attributes[:'parent_legal_entity_id']
      end

      if attributes.key?(:'entity_type')
        self.entity_type = attributes[:'entity_type']
      end

      if attributes.key?(:'ownership_type')
        self.ownership_type = attributes[:'ownership_type']
      end

      if attributes.key?(:'contact_email')
        self.contact_email = attributes[:'contact_email']
      end

      if attributes.key?(:'contact_phone')
        self.contact_phone = attributes[:'contact_phone']
      end

      if attributes.key?(:'business_address_line1')
        self.business_address_line1 = attributes[:'business_address_line1']
      end

      if attributes.key?(:'business_address_line2')
        self.business_address_line2 = attributes[:'business_address_line2']
      end

      if attributes.key?(:'business_city')
        self.business_city = attributes[:'business_city']
      end

      if attributes.key?(:'business_state')
        self.business_state = attributes[:'business_state']
      end

      if attributes.key?(:'business_postal_code')
        self.business_postal_code = attributes[:'business_postal_code']
      end

      if attributes.key?(:'business_country')
        self.business_country = attributes[:'business_country']
      end

      if attributes.key?(:'tax_id_last4')
        self.tax_id_last4 = attributes[:'tax_id_last4']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          organization_id == o.organization_id &&
          legal_name == o.legal_name &&
          parent_legal_entity_id == o.parent_legal_entity_id &&
          entity_type == o.entity_type &&
          ownership_type == o.ownership_type &&
          contact_email == o.contact_email &&
          contact_phone == o.contact_phone &&
          business_address_line1 == o.business_address_line1 &&
          business_address_line2 == o.business_address_line2 &&
          business_city == o.business_city &&
          business_state == o.business_state &&
          business_postal_code == o.business_postal_code &&
          business_country == o.business_country &&
          tax_id_last4 == o.tax_id_last4 &&
          created_at == o.created_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, organization_id, legal_name, parent_legal_entity_id, entity_type, ownership_type, contact_email, contact_phone, business_address_line1, business_address_line2, business_city, business_state, business_postal_code, business_country, tax_id_last4, created_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
