=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Amos
  class LegalEntityEntityType
    INDIVIDUAL_SOLE_PROPRIETORSHIP = "individual_sole_proprietorship".freeze
    CORPORATION = "corporation".freeze
    LIMITED_LIABILITY_COMPANY = "limited_liability_company".freeze
    PARTNERSHIP = "partnership".freeze
    LIMITED_PARTNERSHIP = "limited_partnership".freeze
    GENERAL_PARTNERSHIP = "general_partnership".freeze
    TAX_EXEMPT_ORGANIZATION = "tax_exempt_organization".freeze
    GOVERNMENT_AGENCY = "government_agency".freeze

    def self.all_vars
      @all_vars ||= [INDIVIDUAL_SOLE_PROPRIETORSHIP, CORPORATION, LIMITED_LIABILITY_COMPANY, PARTNERSHIP, LIMITED_PARTNERSHIP, GENERAL_PARTNERSHIP, TAX_EXEMPT_ORGANIZATION, GOVERNMENT_AGENCY].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if LegalEntityEntityType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #LegalEntityEntityType"
    end
  end
end
