=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module Amos
  class LegalEntityApplicationPrincipal < ApiModelBase
    attr_accessor :id

    attr_accessor :legal_entity_application_id

    attr_accessor :first_name

    attr_accessor :last_name

    attr_accessor :email

    attr_accessor :date_of_birth

    attr_accessor :address_line1

    attr_accessor :address_line2

    attr_accessor :city

    attr_accessor :state

    attr_accessor :country

    attr_accessor :postal_code

    attr_accessor :stake_percent

    attr_accessor :contact_phone

    attr_accessor :tax_id_last4

    attr_accessor :title

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'legal_entity_application_id' => :'legal_entity_application_id',
        :'first_name' => :'first_name',
        :'last_name' => :'last_name',
        :'email' => :'email',
        :'date_of_birth' => :'date_of_birth',
        :'address_line1' => :'address_line1',
        :'address_line2' => :'address_line2',
        :'city' => :'city',
        :'state' => :'state',
        :'country' => :'country',
        :'postal_code' => :'postal_code',
        :'stake_percent' => :'stake_percent',
        :'contact_phone' => :'contact_phone',
        :'tax_id_last4' => :'tax_id_last4',
        :'title' => :'title'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'legal_entity_application_id' => :'String',
        :'first_name' => :'String',
        :'last_name' => :'String',
        :'email' => :'String',
        :'date_of_birth' => :'String',
        :'address_line1' => :'String',
        :'address_line2' => :'String',
        :'city' => :'String',
        :'state' => :'String',
        :'country' => :'String',
        :'postal_code' => :'String',
        :'stake_percent' => :'Integer',
        :'contact_phone' => :'String',
        :'tax_id_last4' => :'String',
        :'title' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Amos::LegalEntityApplicationPrincipal` initialize method"
      end

      # Ignore attributes unknown to this client so additive API response fields remain backwards compatible.
      acceptable_attribute_map = self.class.acceptable_attribute_map
      acceptable_json_attribute_map = acceptable_attribute_map.invert
      attributes = attributes.each_with_object({}) { |(k, v), h|
        key = k.respond_to?(:to_sym) ? k.to_sym : k
        if acceptable_attribute_map.key?(key)
          h[key] = v
        elsif acceptable_json_attribute_map.key?(key)
          h[acceptable_json_attribute_map[key]] = v
        end
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'legal_entity_application_id')
        self.legal_entity_application_id = attributes[:'legal_entity_application_id']
      end

      if attributes.key?(:'first_name')
        self.first_name = attributes[:'first_name']
      end

      if attributes.key?(:'last_name')
        self.last_name = attributes[:'last_name']
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      end

      if attributes.key?(:'date_of_birth')
        self.date_of_birth = attributes[:'date_of_birth']
      end

      if attributes.key?(:'address_line1')
        self.address_line1 = attributes[:'address_line1']
      end

      if attributes.key?(:'address_line2')
        self.address_line2 = attributes[:'address_line2']
      end

      if attributes.key?(:'city')
        self.city = attributes[:'city']
      end

      if attributes.key?(:'state')
        self.state = attributes[:'state']
      end

      if attributes.key?(:'country')
        self.country = attributes[:'country']
      end

      if attributes.key?(:'postal_code')
        self.postal_code = attributes[:'postal_code']
      end

      if attributes.key?(:'stake_percent')
        self.stake_percent = attributes[:'stake_percent']
      end

      if attributes.key?(:'contact_phone')
        self.contact_phone = attributes[:'contact_phone']
      end

      if attributes.key?(:'tax_id_last4')
        self.tax_id_last4 = attributes[:'tax_id_last4']
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          legal_entity_application_id == o.legal_entity_application_id &&
          first_name == o.first_name &&
          last_name == o.last_name &&
          email == o.email &&
          date_of_birth == o.date_of_birth &&
          address_line1 == o.address_line1 &&
          address_line2 == o.address_line2 &&
          city == o.city &&
          state == o.state &&
          country == o.country &&
          postal_code == o.postal_code &&
          stake_percent == o.stake_percent &&
          contact_phone == o.contact_phone &&
          tax_id_last4 == o.tax_id_last4 &&
          title == o.title
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, legal_entity_application_id, first_name, last_name, email, date_of_birth, address_line1, address_line2, city, state, country, postal_code, stake_percent, contact_phone, tax_id_last4, title].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
