=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Amos
  class PaymentMethodType
    CARD = "card".freeze
    BANK_ACCOUNT = "bank_account".freeze
    GOOGLEPAY = "googlepay".freeze
    APPLEPAY = "applepay".freeze

    def self.all_vars
      @all_vars ||= [CARD, BANK_ACCOUNT, GOOGLEPAY, APPLEPAY].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if PaymentMethodType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #PaymentMethodType"
    end
  end
end
