=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Amos
  class RefundStateType
    PENDING = "pending".freeze
    PROCESSING = "processing".freeze
    REQUIRES_REVIEW = "requires_review".freeze
    SUCCEEDED = "succeeded".freeze
    CANCELLED = "cancelled".freeze
    FAILED = "failed".freeze

    def self.all_vars
      @all_vars ||= [PENDING, PROCESSING, REQUIRES_REVIEW, SUCCEEDED, CANCELLED, FAILED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if RefundStateType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #RefundStateType"
    end
  end
end
