=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Amos
  class UsStateType
    AK = "AK".freeze
    AL = "AL".freeze
    AR = "AR".freeze
    AZ = "AZ".freeze
    CA = "CA".freeze
    CO = "CO".freeze
    CT = "CT".freeze
    DE = "DE".freeze
    FL = "FL".freeze
    GA = "GA".freeze
    HI = "HI".freeze
    IA = "IA".freeze
    ID = "ID".freeze
    IL = "IL".freeze
    IN = "IN".freeze
    KS = "KS".freeze
    KY = "KY".freeze
    LA = "LA".freeze
    MA = "MA".freeze
    MD = "MD".freeze
    ME = "ME".freeze
    MI = "MI".freeze
    MN = "MN".freeze
    MO = "MO".freeze
    MS = "MS".freeze
    MT = "MT".freeze
    NC = "NC".freeze
    ND = "ND".freeze
    NE = "NE".freeze
    NH = "NH".freeze
    NJ = "NJ".freeze
    NM = "NM".freeze
    NV = "NV".freeze
    NY = "NY".freeze
    OH = "OH".freeze
    OK = "OK".freeze
    OR = "OR".freeze
    PA = "PA".freeze
    RI = "RI".freeze
    SC = "SC".freeze
    SD = "SD".freeze
    TN = "TN".freeze
    TX = "TX".freeze
    UT = "UT".freeze
    VA = "VA".freeze
    VT = "VT".freeze
    WA = "WA".freeze
    WI = "WI".freeze
    WV = "WV".freeze
    WY = "WY".freeze

    def self.all_vars
      @all_vars ||= [AK, AL, AR, AZ, CA, CO, CT, DE, FL, GA, HI, IA, ID, IL, IN, KS, KY, LA, MA, MD, ME, MI, MN, MO, MS, MT, NC, ND, NE, NH, NJ, NM, NV, NY, OH, OK, OR, PA, RI, SC, SD, TN, TX, UT, VA, VT, WA, WI, WV, WY].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if UsStateType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #UsStateType"
    end
  end
end
