=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Amos
  # Body POSTed to a webhook endpoint for an event delivery.
  class WebhookEventPayload < ApiModelBase
    # Stable event id for this delivery. Identical across retries of the same event; use for idempotent handling. 
    attr_accessor :id

    # Id of the webhook endpoint that received this delivery.
    attr_accessor :webhook_id

    attr_accessor :event

    # Event-specific payload keyed by resource descriptor.
    attr_accessor :data

    # Additional metadata key-value pairs
    attr_accessor :metadata

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'webhook_id' => :'webhook_id',
        :'event' => :'event',
        :'data' => :'data',
        :'metadata' => :'metadata'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'webhook_id' => :'String',
        :'event' => :'WebhookEventType',
        :'data' => :'Hash<String, Object>',
        :'metadata' => :'Hash<String, String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Amos::WebhookEventPayload` initialize method"
      end

      # Ignore attributes unknown to this client so additive API response fields remain backwards compatible.
      acceptable_attribute_map = self.class.acceptable_attribute_map
      acceptable_json_attribute_map = acceptable_attribute_map.invert
      attributes = attributes.each_with_object({}) { |(k, v), h|
        key = k.respond_to?(:to_sym) ? k.to_sym : k
        if acceptable_attribute_map.key?(key)
          h[key] = v
        elsif acceptable_json_attribute_map.key?(key)
          h[acceptable_json_attribute_map[key]] = v
        end
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'webhook_id')
        self.webhook_id = attributes[:'webhook_id']
      else
        self.webhook_id = nil
      end

      if attributes.key?(:'event')
        self.event = attributes[:'event']
      else
        self.event = nil
      end

      if attributes.key?(:'data')
        if (value = attributes[:'data']).is_a?(Hash)
          self.data = value
        end
      else
        self.data = nil
      end

      if attributes.key?(:'metadata')
        if (value = attributes[:'metadata']).is_a?(Hash)
          self.metadata = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @webhook_id.nil?
        invalid_properties.push('invalid value for "webhook_id", webhook_id cannot be nil.')
      end

      if @event.nil?
        invalid_properties.push('invalid value for "event", event cannot be nil.')
      end

      if @data.nil?
        invalid_properties.push('invalid value for "data", data cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @webhook_id.nil?
      return false if @event.nil?
      return false if @data.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] webhook_id Value to be assigned
    def webhook_id=(webhook_id)
      if webhook_id.nil?
        fail ArgumentError, 'webhook_id cannot be nil'
      end

      @webhook_id = webhook_id
    end

    # Custom attribute writer method with validation
    # @param [Object] event Value to be assigned
    def event=(event)
      if event.nil?
        fail ArgumentError, 'event cannot be nil'
      end

      @event = event
    end

    # Custom attribute writer method with validation
    # @param [Object] data Value to be assigned
    def data=(data)
      if data.nil?
        fail ArgumentError, 'data cannot be nil'
      end

      @data = data
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          webhook_id == o.webhook_id &&
          event == o.event &&
          data == o.data &&
          metadata == o.metadata
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, webhook_id, event, data, metadata].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
