=begin
#Amos Pay API

#Amos Pay API spec

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Amos
  class WebhookEventType
    CHARGE_CANCELLED = "charge.cancelled".freeze
    CHARGE_CREATED = "charge.created".freeze
    CHARGE_ERRORED = "charge.errored".freeze
    CHARGE_FAILED = "charge.failed".freeze
    CHARGE_PROCESSING = "charge.processing".freeze
    CHARGE_REQUIRES_CAPTURE = "charge.requires_capture".freeze
    CHARGE_REQUIRES_CONFIRMATION = "charge.requires_confirmation".freeze
    CHARGE_REQUIRES_REVIEW = "charge.requires_review".freeze
    CHARGE_SUCCEEDED = "charge.succeeded".freeze
    CUSTOMER_CREATED = "customer.created".freeze
    CUSTOMER_UPDATED = "customer.updated".freeze
    LEGAL_ENTITY_CREATED = "legal_entity.created".freeze
    LEGAL_ENTITY_UPDATED = "legal_entity.updated".freeze
    LEGAL_ENTITY_PRINCIPAL_CREATED = "legal_entity_principal.created".freeze
    LEGAL_ENTITY_PRINCIPAL_UPDATED = "legal_entity_principal.updated".freeze
    MERCHANT_CREATED = "merchant.created".freeze
    MERCHANT_UPDATED = "merchant.updated".freeze
    PAYMENT_INTENT_CANCELLED = "payment_intent.cancelled".freeze
    PAYMENT_INTENT_CREATED = "payment_intent.created".freeze
    PAYMENT_INTENT_ERRORED_AUTHORIZATION = "payment_intent.errored_authorization".freeze
    PAYMENT_INTENT_ERRORED_CAPTURE = "payment_intent.errored_capture".freeze
    PAYMENT_INTENT_ERRORED_SALE = "payment_intent.errored_sale".freeze
    PAYMENT_INTENT_PROCESSING_AUTHORIZATION = "payment_intent.processing_authorization".freeze
    PAYMENT_INTENT_PROCESSING_CAPTURE = "payment_intent.processing_capture".freeze
    PAYMENT_INTENT_PROCESSING_SALE = "payment_intent.processing_sale".freeze
    PAYMENT_INTENT_REQUIRES_CAPTURE = "payment_intent.requires_capture".freeze
    PAYMENT_INTENT_REQUIRES_CONFIRMATION = "payment_intent.requires_confirmation".freeze
    PAYMENT_INTENT_REQUIRES_PAYMENT_METHOD = "payment_intent.requires_payment_method".freeze
    PAYMENT_INTENT_REQUIRES_REVIEW = "payment_intent.requires_review".freeze
    PAYMENT_INTENT_SUCCEEDED = "payment_intent.succeeded".freeze
    PROCESSOR_TRANSACTION_COMPLETED = "processor_transaction.completed".freeze
    RECONCILIATION_CREATED = "reconciliation.created".freeze
    REFUND_CANCELLED = "refund.cancelled".freeze
    REFUND_CREATED = "refund.created".freeze
    REFUND_FAILED = "refund.failed".freeze
    REFUND_PENDING = "refund.pending".freeze
    REFUND_PROCESSING = "refund.processing".freeze
    REFUND_REQUIRES_REVIEW = "refund.requires_review".freeze
    REFUND_SUCCEEDED = "refund.succeeded".freeze
    VOID_CREATED = "void.created".freeze
    VOID_FAILED = "void.failed".freeze
    VOID_PENDING = "void.pending".freeze
    VOID_PROCESSING = "void.processing".freeze
    VOID_REQUIRES_REVIEW = "void.requires_review".freeze
    VOID_SUCCEEDED = "void.succeeded".freeze

    def self.all_vars
      @all_vars ||= [CHARGE_CANCELLED, CHARGE_CREATED, CHARGE_ERRORED, CHARGE_FAILED, CHARGE_PROCESSING, CHARGE_REQUIRES_CAPTURE, CHARGE_REQUIRES_CONFIRMATION, CHARGE_REQUIRES_REVIEW, CHARGE_SUCCEEDED, CUSTOMER_CREATED, CUSTOMER_UPDATED, LEGAL_ENTITY_CREATED, LEGAL_ENTITY_UPDATED, LEGAL_ENTITY_PRINCIPAL_CREATED, LEGAL_ENTITY_PRINCIPAL_UPDATED, MERCHANT_CREATED, MERCHANT_UPDATED, PAYMENT_INTENT_CANCELLED, PAYMENT_INTENT_CREATED, PAYMENT_INTENT_ERRORED_AUTHORIZATION, PAYMENT_INTENT_ERRORED_CAPTURE, PAYMENT_INTENT_ERRORED_SALE, PAYMENT_INTENT_PROCESSING_AUTHORIZATION, PAYMENT_INTENT_PROCESSING_CAPTURE, PAYMENT_INTENT_PROCESSING_SALE, PAYMENT_INTENT_REQUIRES_CAPTURE, PAYMENT_INTENT_REQUIRES_CONFIRMATION, PAYMENT_INTENT_REQUIRES_PAYMENT_METHOD, PAYMENT_INTENT_REQUIRES_REVIEW, PAYMENT_INTENT_SUCCEEDED, PROCESSOR_TRANSACTION_COMPLETED, RECONCILIATION_CREATED, REFUND_CANCELLED, REFUND_CREATED, REFUND_FAILED, REFUND_PENDING, REFUND_PROCESSING, REFUND_REQUIRES_REVIEW, REFUND_SUCCEEDED, VOID_CREATED, VOID_FAILED, VOID_PENDING, VOID_PROCESSING, VOID_REQUIRES_REVIEW, VOID_SUCCEEDED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if WebhookEventType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #WebhookEventType"
    end
  end
end
